### ISSUE TITLE
faqs in the docs

### ISSUE THREAD

**Issue by hgomersall** [myhdl/myhdl#187]
I suggest that the faqs that currently live on the website are merged into the docs, this way it is possible to raise PRs with new additions.

I'm happy to do this if it is deemed sensible.

**Comment by jck** [comment]
This sounds like a good idea

**Comment by cfelton** [comment]
You can still raise [PRs](https://github.com/myhdl/site-myhdl) with the FAQ in there current spot.

It will be easier for us to update the FAQs where it currently lives.
