### ISSUE TITLE
Cannot run myhdl cookbook example on Windows 10

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [myhdl/myhdl#265]
Hi,
I am trying to run StopWatch example and having some issues
What I did is:
1. Download and install Python 3.7
2. Installed MyHDL via pip install myhdl
3. Run any test or examples and get next error in console
![image](https://user-images.githubusercontent.com/11254187/42446792-dfefc704-83ba-11e8-80f0-723e322a5434.png)

4. Try to install from github using setup.py, got next errors
![image](https://user-images.githubusercontent.com/11254187/42446846-1f061fa6-83bb-11e8-9dda-02c90dc6ba53.png)

![image](https://user-images.githubusercontent.com/11254187/42446854-263d6e8c-83bb-11e8-9eb4-ec5c6220218d.png)

![image](https://user-images.githubusercontent.com/11254187/42446877-35ecef6a-83bb-11e8-83cd-ba763517ea0b.png)

What am I doing wrong?

Thanks,
Regards,
Evgeny

**Comment by josyb** [comment]
You have tripped over the *async* reserved keyword in Python 3.7 which conflicts with the ```async=``` argument in MyHDL's ```ResetSignal()```
Currently the best option is to revert to Python 3.6

**Comment by cfelton** [comment]
We need a FAQ for this :)

**Comment by zzsczz** [comment]
python 3.11.9  x64 windows  version  works with myhdl  git version
