### ISSUE TITLE
Python 3.7 compatibility (use of `async` keyword as variable)

### ISSUE THREAD

**Issue by dries007** [myhdl/myhdl#268]
`async` is now a keyword in 3.7, so it can no longer be used as a variable name.

This is the case in [_always_seq](https://github.com/myhdl/myhdl/blob/master/myhdl/_always_seq.py) and in [conversion/_toVHDL](https://github.com/myhdl/myhdl/blob/master/myhdl/conversion/_toVHDL.py).

A simple regex search (`\basync\b`) showed this was the only place where this variable name was used.
I replaced them in my local copy with `async_` and the simple hello world example works.

**Comment by josyb** [comment]
This is being addressed in PR #267 and #264.

**Comment by dries007** [comment]
Oh, I'm sorry for not looking further.
