### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by xd009642** [myhdl/myhdl#294]
I was just wondering when the next version would be released as myhdl doesn't work for my python install as async is used as a variable. However, this was fixed and merged in #264. So when will the next version be out so I can use this with my latest install of python?

**Comment by cfelton** [comment]
@xd009642 there is no specific date for the next release.  There are a couple items that should be addressed before the next release.

You can pull the latest and it should resolve the 3.7 issues or use < 3.7.
