### ISSUE TITLE
Pledge to drop Python 2 support

### ISSUE THREAD

**Issue by jck** [myhdl/myhdl#301]
https://python3statement.org/

Many major projects including pytest, ipython, pandas and numpy are dropping Python 2 support.

We can simplify some of our code, and explore Python 3 only features such as asyncio by dropping Python 2 support in a later version.

We should decide on a timeline for the first Python 3 only version.

**Comment by hashhsah** [comment]
does python3 only feature mean python3.5+, such as async/await?

**Comment by NicoPy** [comment]
This is ok for me.
I only use Python3 with MyHDL.

**Comment by hugovk** [comment]
Please see PR https://github.com/myhdl/myhdl/pull/307.
