### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by VictorTagayun** [myhdl/myhdl#305]
Do you have a forum?

**Comment by josyb** [comment]
'chat': https://gitter.im/myhdl/myhdl
'forum': http://discourse.myhdl.org

It is a bit cocky to label your post as an *enhancement* as with a bit of searching you should have been able to find the above links yourself. Google returns the above links as the top result for "myhdl forum"and "myhdl chat" . And myhdl's web-site: http://www.myhdl.org/support/community.html gives these pointers too ...

**Comment by VictorTagayun** [comment]
Sorry, did not see that one.
