### ISSUE TITLE
Python3.7 makes async a reserved keyword

### ISSUE THREAD

**Issue by tomtor** [myhdl/myhdl#312]
Summary

## System information
```
MyHDL Version: 0.10
Python Version: 3.7
```
Myhdl source files `_always_seq.py` and `_toVHDL.py` use the new reserved keyword `async` as identifier. I had to change this to `myasync` as quick work around.

**Comment by josyb** [comment]
This has been addressed in the *tip* 
_Revision: dfea638ef32c9a3774f6c703f23e17464cc856f9
Author: Alex Forencich <alex@alexforencich.com>
Date: 14/08/2018 23:46:32
Message:
Rename async to isasync to resolve conflict with python 3.7_

You may want to pull the changes (every now and then)
