### ISSUE TITLE
move CI from travis to github actions

### ISSUE THREAD

**Issue by jck** [myhdl/myhdl#334]
benefits:
- CI and results integrated in github UI
- Linux, macOS and windows in one place

**Comment by davekeeshan** [comment]
This issue is partially done, linux CI is now on github actions #369

macOS might be easy enough (?) but installing ghdl and iverilog on windows might be a little harder to do

**Comment by jck** [comment]
awesome. thanks!
we should probably add some tickets in the backlog for windows and mac
