### ISSUE TITLE
cosimulation

### ISSUE THREAD

**Issue by olisnr** [myhdl/myhdl#419]
i have the question where i find the ./myhdl.vpi. do i have to build one from the myHDL-source directory and copy it in the python-directory?, or is it already somewhere installed? or should it be build automatic in the cosimulation-function?

**Comment by josyb** [comment]
You have to build it
And copy it to C:\Programs\iverilog\lib\ivl - as on my Windows machine; it will be different on Linux
I have a built version for Windows :) which is not in the repository :(

**Comment by olisnr** [comment]
thanks a lot, i also could build the one for modelsim after adding a line in the makefile:
INCS=-I /usr/local/microchip/Libero_SoC_v2022.3/ModelSimPro/modeltech/include
