### ISSUE TITLE
New release or new version to pypi?

### ISSUE THREAD

**Issue by TurnOffNOD** [myhdl/myhdl#441]
Since pypi version is quite behind the current development status, will there be new release in the near future? Or new dev version upload to pypi without new release?

**Comment by josyb** [comment]
Actyally this is no longer the case; we update the PyPi after every PR merge. Currently we are at 0.11.49.
Unfortunately I haven't  updated MyHDL's *readme.md* to relefect that (yet, will try to do so at next merge).

**Comment by TurnOffNOD** [comment]
> Actyally this is no longer the case; we update the PyPi after every PR merge. Currently we are at 0.11.49. Unfortunately I haven't updated MyHDL's _readme.md_ to relefect that (yet, will try to do so at next merge).

Oh, I see. I installed from pip as a result.
